/*
 * generated by Xtext 2.19.0
 */
package org.jonpas.asel.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.jonpas.asel.ASELhRuntimeModule
import org.jonpas.asel.ASELhStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ASELhIdeSetup extends ASELhStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ASELhRuntimeModule, new ASELhIdeModule))
	}
	
}
