/*
 * generated by Xtext 2.19.0
 */
package org.jonpas.asel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ASELhStandaloneSetup extends ASELhStandaloneSetupGenerated {

	def static void doSetup() {
		new ASELhStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
