/*
 * generated by Xtext 2.19.0
 */
package org.jonpas.asel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ASELStandaloneSetup extends ASELStandaloneSetupGenerated {

	def static void doSetup() {
		new ASELStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
